### ISSUE TITLE
Add gas fees stats

### ISSUE THREAD

**Issue by ethedev** [yam-finance/degenerative#15]
# 🛢️ Gas Fees Stats
We need to add on the **uGas** asset page, a section where we show gas statistics used by the connected address.
The data can be added as simple labels on the page for the moment.

Labels showing several things in relation to the connected address:
- [ ] overall value spent on gas for all transactions so far, value in eth and usd
- [ ] average price of gas spent, in gwei
- [ ] number of transactions so far
- [ ] failed transactions count
- [ ] value of failed transactions, value in eth and usd
- [ ] add switch date: today, this week/month/year and custom date range A - B, to populate results

Note the value of usd can be calculated of what the current eth price is at.

**Comment by self-coding-crab** [comment]
@ethedev Would you assign it to me?
