### ISSUE TITLE
Add prevent million clicks

### ISSUE THREAD

**Issue by ethedev** [yam-finance/degenerative#41]
Currently on the asset page if you click the approve button or other buttons that holds any interaction to metamask you will be able to click it more than once which will result with multiple and unwanted metamask windows to open. We dont want that, and we need to add a check on the button click waiting for some sort of result and act accordingly after the button is clicked to prevent such behavior.

**Comment by sali0** [comment]
Notes:
- Able to click approve multiple times with multiple popups. Only want function triggered once.
